model:
  type: Vishwamai
  size: 27b
  layers: 48
  hidden_size: 8192
  attention_heads: 64
  dropout: 0.1

training:
  batch_size: 4
  learning_rate: 3e-5
  epochs: 10
  optimizer: AdamW
  scheduler: linear

data:
  train_dataset: path/to/train_dataset
  validation_dataset: path/to/validation_dataset

evaluation:
  metrics:
    - name: Perplexity
    - name: BLEU
    - name: ROUGE
