model:
  type: Vishwamai
  size: 9b
  layers: 36
  hidden_size: 5120
  attention_heads: 40
  dropout: 0.1

training:
  batch_size: 8
  learning_rate: 3e-5
  epochs: 10
  optimizer: AdamW
  scheduler: linear

data:
  train_dataset: datasets/train.json
  validation_dataset: datasets/dev.json

evaluation:
  metrics:
    - name: Perplexity
    - name: BLEU
    - name: ROUGE
