model:
  type: Vishwamai
  size: 7b
  layers: 32
  hidden_size: 4096
  attention_heads: 32
  dropout: 0.1

training:
  batch_size: 16
  learning_rate: 3e-5
  epochs: 10
  optimizer: AdamW
  scheduler: linear

data:
  train_dataset: datasets/train.json
  validation_dataset: datasets/dev.json

evaluation:
  metrics:
    - name: Perplexity
    - name: BLEU
    - name: ROUGE
