name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Debug working directory
      run: |
        pwd
        ls -la

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint mypy

    - name: Run tests
      run: pytest tests/

    - name: Run linting
      run: pylint **/*.py

    - name: Run type checking
      run: mypy .